import { Pact, Matchers } from '@pact-foundation/pact';
import supertest from 'supertest';
import express, { Router } from 'express';
import app from '../app'; // Import your Express app
import { router } from '../src/routes/todo.routes';

const path = require('path');

const provider = new Pact({
    consumer: 'TodoConsumer',
    provider: 'TodoProvider',
    port: 8000, // Choose a suitable port
    log: path.resolve(process.cwd(), 'logs', 'pact.log'),
    dir: path.resolve(process.cwd(), 'pacts'),
});

const app = express();
app.use('/', router);
beforeAll(() => provider.setup());
afterEach(() => provider.verify());
afterAll(() => provider.finalize());

describe('Todo Provider', () => {
    beforeAll(() => {
        server.listen(8000, () => {
            console.log(`Provider service started on 8000`);
        });
    });

    it('should validate the expectations of the consumer', async () => {
        const opts = {
            provider: 'TodoProvider',
            providerBaseUrl: `http://localhost:8000`,
            providerStatesSetupUrl: `http://localhost:8000/setup`,
            pactUrls: [
                path.resolve(
                    process.cwd(),
                    './pacts/pact.json'
                ),
            ],
        };

        //validate the pact generated by the consumer is valid, by executing it against the running service provider
        const output = await new Pact.Verifier(opts).verifyProvider();
        console.log('Pact Verification Complete!')
        console.log(output)
    });
});